### ISSUE TITLE
Question - How I can manage diferenciated speeds using ECS

### ISSUE THREAD

**Issue by fraespre** [AmstradGameDevChallenge/BASICvsC-RPG#2]
Hello everyone,

First, I would like to thank the chance to learn the ECS concepts.

I write here because I have a doubt regarding with a teorical scenario, to see if the current structure could bear it or I need to upgrade it.

This is more or less the main loop of the game. Well, after the sys_render_update, I have a "throttle limit" to keep stable the framerate:

![mainLoop](https://user-images.githubusercontent.com/6942084/81345494-de871b80-90b8-11ea-8b82-3468cc1c8d07.png)

I'm thinking that in the game, the player have the possibility to get a power up and speed up his movements.
I suppose that the easy way would be to update the player increments into the Physics System. 
But other way, would be change the framerate of the main loop for the player. For example, evaluate the player Entity every 2 frames, instead every 4 frames (as the rest of Entities). However I guess this way would affect several Systems (input, physics, collision, render ...), which must work synchronized.

I would like you comment how I could handle the differentiated speeds approach, using the ECS guidelines.

Thanks in advanced,

**Comment by lronaldo** [comment]
Hi @fraespre 

   For the idea you purpose, which is modulating the speed of player movements, I would not consider linking it to processing framerate. These are two separate concepts with way different consequences. In order to modulate player speed, I would always refer to physic system and use fixed point arithmetic. I have some videos on this subject. There are many ways to do this, and you can either speed up or slow down player movements at will. That will be my preferred option, which is simple, flexible and intuitive. 

Adjusting processing framerate for entities (not just the player) is the option I use when I want to distribute available processing power over frames. For instance, enemies do not need to take decisions every frame. In fact, if they do, they may have advantage over the player. If your framerate was 25 fps, it is unplausible for a human to take 25 different decisions over the course of a second. In fact, even pressing 25 different key combinations over a single second would be almost impossible for a human. So, it follows that an enemy show adjust their decision rate accordingly, and then enemies could process their AI algorithms 2-3 times per second and be perfectly right. If you then distribute enemy AI processing over different frames, that would be a form of scheduling to do a better use of resources. And you can take this idea even further and make visible enemies process 2-3 times per second, while non-visible enemies could process 1 time every 2 seconds. As you are not seeing them, they can even do different things, as long as the result seems plausible to the user. This is known as AI Level of Detail (AI LoD).

So, I would reserve playing with Scheduling, LoD and similar techniques for the case of adjusting processing resources to the game, but not to modulate player speed. That matter is better achieved using the physics system and fixed point arithmetic.

**Comment by fraespre** [comment]
Thank you a lot @lronaldo  for your response. 
Especially I liked your brief explanation about "AI LoD". This is something that I had started to think, but I didn't know there was a specific concept neither theory related. I will search it.

Thanks again,
